name: Feature request
description: Предложить улучшение
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему решает фича
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Предложение решения
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Дополнительный контекст
